// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnwNW-GaHH8nw5R--UM5iC_zMIb4x6Wfo',
    appId: '1:999507255560:web:7a0d9957709e335e3bccbd',
    messagingSenderId: '999507255560',
    projectId: 'smart-brain-care',
    authDomain: 'smart-brain-care.firebaseapp.com',
    storageBucket: 'smart-brain-care.firebasestorage.app',
    measurementId: 'G-KZRRYSWEZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvDbO6ukWt_3f5wF7aXgt0pM6WmKooAc',
    appId: '1:999507255560:android:091305f8797fae7a3bccbd',
    messagingSenderId: '999507255560',
    projectId: 'smart-brain-care',
    storageBucket: 'smart-brain-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE-YrrIoIviUsCXMos1u79SWoTtJvB7wo',
    appId: '1:999507255560:ios:d76c656bd2635b783bccbd',
    messagingSenderId: '999507255560',
    projectId: 'smart-brain-care',
    storageBucket: 'smart-brain-care.firebasestorage.app',
    iosClientId: '999507255560-h1l4stib5m7vs49d46kr1sj6bccjes9u.apps.googleusercontent.com',
    iosBundleId: 'com.brainwave.brainWaveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE-YrrIoIviUsCXMos1u79SWoTtJvB7wo',
    appId: '1:999507255560:ios:d76c656bd2635b783bccbd',
    messagingSenderId: '999507255560',
    projectId: 'smart-brain-care',
    storageBucket: 'smart-brain-care.firebasestorage.app',
    iosClientId: '999507255560-h1l4stib5m7vs49d46kr1sj6bccjes9u.apps.googleusercontent.com',
    iosBundleId: 'com.brainwave.brainWaveFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnwNW-GaHH8nw5R--UM5iC_zMIb4x6Wfo',
    appId: '1:999507255560:web:1c74dc343cf40ac33bccbd',
    messagingSenderId: '999507255560',
    projectId: 'smart-brain-care',
    authDomain: 'smart-brain-care.firebaseapp.com',
    storageBucket: 'smart-brain-care.firebasestorage.app',
    measurementId: 'G-D3YSBWTMRY',
  );
}
